# Generated by Django 3.2.23 on 2024-02-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
