# Generated by Django 3.2.23 on 2024-02-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_applieddiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
    ]
