# Generated by Django 3.2.23 on 2024-01-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_genres_game_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
