# Generated by Django 3.2.23 on 2024-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_release_date_game_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviews',
        ),
        migrations.AddField(
            model_name='game',
            name='reviews',
            field=models.ManyToManyField(to='games.Reviews'),
        ),
    ]
