# Generated by Django 3.2.23 on 2024-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='games.Review'),
        ),
    ]
