# Generated by Django 3.2.23 on 2024-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
