# Generated by Django 3.2.23 on 2024-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
        ('games', '0013_auto_20240220_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='wishlist.Wishlist'),
        ),
    ]
