# Generated by Django 3.2.23 on 2024-02-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
        ('games', '0014_game_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='games_in_wishlist', to='wishlist.Wishlist'),
        ),
    ]
