# Generated by Django 3.2.23 on 2024-03-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20240229_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
